# Generated by Django 5.0.4 on 2024-10-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesae', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='state',
            field=models.CharField(default='off', max_length=3),
        ),
    ]
