# Generated by Django 5.0.4 on 2024-10-09 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesae', '0002_schedule_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='state',
        ),
    ]
