# Generated by Django 5.0.4 on 2024-10-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesae', '0003_remove_schedule_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
