# Generated by Django 5.0.4 on 2024-10-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesae', '0004_schedule_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
