<LoginScreen>:
    Image:
        source: "fond1.png"
        size_hint: (1, 1)
        allow_stretch: True
        keep_ratio: False
        pos_hint: {'x': 0, 'y': 0}

    Label:
        text: "Connexion"
        font_size: "48dp"
        halign: "center"
        color: "#CCCCCC"
        pos_hint: {'center_y': .8}

    TextInput:
        id: username_input
        hint_text: "Username"
        font_size: "20dp"
        size_hint_x: 0.8
        size_hint_y: None
        height: "40dp"
        pos_hint: {'center_x': .5, 'center_y': .55}
        

    TextInput:
        id: password_input
        hint_text: "Password"
        font_size: "20dp"
        size_hint_x: 0.8
        size_hint_y: None
        height: "40dp"
        pos_hint: {'center_x': .5, 'center_y': .45}
        password: True

    Button:
        text: 'Connexion'
        font_size: "20dp"
        size_hint_x: 0.9
        size_hint_y: None
        height: "50dp"
        pos_hint: {'center_x': .5, 'center_y': .25}
        on_release: root.on_login()

    Label:
        id: message_label
        text: ""
        font_size: "20dp"
        color: "#D90115"
        pos_hint: {'center_x': .5, 'center_y': .15}


















<SuccessScreen>:
    Image:
        source: "fond1.png"
        size_hint: (1, 1)
        allow_stretch: True
        keep_ratio: False
        pos_hint: {'x': 0, 'y': 0}

    Label:
        text: "RasberryPI page"
        font_size: "45dp"
        halign: "center"
        color: "#CCCCCC"
        pos_hint: {'center_y': .9}

    Button:
        text: "Déconnexion"
        size_hint_y: None
        height: "50dp"
        on_release: root.on_back()

    Button:
        text:"ON/OFF"
        size_hint_x: 0.8
        size_hint_y: None
        height: "50dp"
        pos_hint: {'center_x': .5, 'center_y': .75}
    
        